### ISSUE TITLE
cast-align werror on mips

### ISSUE THREAD

**Issue by zhongtianxie** [lcp/mokutil#28]
mokutil.c: In function 'sb_state':
mokutil.c:1822:21: error: cast increases required alignment of target type [-Werror=cast-align]
   state = (int32_t)*(uint32_t *)data;
                     ^
mokutil.c:1824:21: error: cast increases required alignment of target type [-Werror=cast-align]
   state = (int32_t)*(uint16_t *)data;
                     ^
cc1: all warnings being treated as errors

**Comment by andypost** [comment]
Getting the same for Alpinelinux package (only 32bits)
```
mokutil.c: In function 'generate_pw_hash':
mokutil.c:2038:16: error: comparison of integer expressions of different signedness: 'unsigned int' and 'int' [-Werror=sign-compare]
 2038 |  if (salt_size > settings_len - (next - settings)) {
      |                ^
mv -f .deps/mokutil-password-crypt.Tpo .deps/mokutil-password-crypt.Po
```
