### ISSUE TITLE
I am going to uninstall ubuntu, do I need to considering uninstall mok?

### ISSUE THREAD

**Issue by xiongmao86** [lcp/mokutil#29]
I have a laptop try ubuntu system. The drivers are not fit. And now I am trying to uninstall it, the tutorial says assign efi partition a driver name and remove the ubuntu directory, and then I can remove the whole ext partition. I am wondering do I need to do additional steps to remove mok? I have try to search on net, but answers are vague, and I didn't find docs about mok.

**Comment by lcp** [comment]
It depends. If you're sure that those keys in MokList won't be used afterward, you can type "mokutil --reset" to clear all keys in MokList. Or furthermore, reset the firmware if you want an absolutely clean environment.

**Comment by xiongmao86** [comment]
Thank you for your help, @lcp, so  installing ubuntu with property driver actually change uefi bios firmware? I do want to change the firmware back if possible, I search `mokutil reset firmware` on `cn.bing.com` but I don't get relevant answer, do I use wrong keyword?

**Comment by xiongmao86** [comment]
Is it possible to damage bios functioning when I am resetting the uefi firmware, and what is the result of left it unchanged?

**Comment by lcp** [comment]
If you want to reset the firmware, you have to enter the UEFI firmware UI and search for the option like "Reset to factory settings", and this is nothing to do with mokutil. "mokutil --reset" just notifies MokManager.efi to clear the MokList variable stored in NVRAM.

In general, doing a factory reset won't damage your BIOS but clear up your current settings. You may need to tweak your BIOS after a factory reset.

**Comment by xiongmao86** [comment]
Thank you very much for your help @lcp, I have no other questions.
