### ISSUE TITLE
Estimated date for a 0.5.0 release

### ISSUE THREAD

**Issue by martinezjavier** [lcp/mokutil#38]
The last 0.4.0 release was on May, 2019 and there have been a lot of changes since then. Is there a plan to have a new release soon ?

**Comment by lcp** [comment]
Yeah, the number of changes justifies a version bump. I'll review the change log tomorrow and see if there is any thing missed before bumping the version.

**Comment by martinezjavier** [comment]
Great, thanks. I just found another bug and opened PR #40

**Comment by lcp** [comment]
I'm working on a few more updates and planning to release 0.5.0 this week.

**Comment by lcp** [comment]
Sorry for the delay, got busy recently either at work or life. Kind of missing the good old days of being single :p
Anyway, just tagged 0.5.0.
