### ISSUE TITLE
build problem

### ISSUE THREAD

**Issue by dfdtc** [lcp/mokutil#42]
I have raised a issue of _problem of failed to delete secure boot state_ ,and i tried to install latest version to fix it. And it told me that i haven't got efivar, but I'm sure I've installed it(with apt).

**Comment by lcp** [comment]
You need to install the devel package such as efivar-devel or libefivar-dev, depending on the distro you use.

**Comment by dfdtc** [comment]
sorry I'm late. according to my testing(I built a grub image with all necessary packages and sign all .efi files manually). Kail may NOT support the secure boot, some clues showed that the kernel was support it.
