### ISSUE TITLE
Incorrect version info printed with "-v" in 0.7.0

### ISSUE THREAD

**Issue by nkkuntal** [lcp/mokutil#77]
Hi,

I built and installed latest release v0.7.0. However, the version is not updated in `configure.ac`, resulting in the older version being printed when using the `-v` command-line option.

```
$ mokutil -v
0.6.0
```

**Comment by lcp** [comment]
Oops, I forgot the bump the version. I'm planning to release 0.7.1 after merging a few queuing patches. Will fix the versioning in 0.7.1.

**Comment by lcp** [comment]
Fixed the versioning issue in 0.7.1.

**Comment by nkkuntal** [comment]
Awesome! Thanks :)
