### ISSUE TITLE
What do you mean by "shim"?

### ISSUE THREAD

**Issue by korpe1** [lcp/mokutil#80]
"The utility to manipulate machines owner keys which managed in shim"
"mokutil is a tool to import or delete the machines owner keys (MOK) stored in the database of shim."

What do you mean by "shim"?

**Comment by lcp** [comment]
'shim' is the first stage bootloader for Linux to support UEFI Secure Boot:
https://github.com/rhboot/shim

**Comment by korpe1** [comment]
> 'shim' is the first stage bootloader for Linux to support UEFI Secure Boot: https://github.com/rhboot/shim

Is shim the binary that the distros ask Microsoft or other CA to sign?

**Comment by lcp** [comment]
Yes

**Comment by lcp** [comment]
Closing this issue sine there is no further question.
